version: "3.9"

services:
  app:
    build:
      context: .
    image: django-celery/app
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
  celery:
    image: django-celery/app
    restart: always
    command: "celery -A demo_project worker -l info --concurrency=8"
    depends_on:
      - app
      - redis
      - rabbitmq
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
